### ISSUE TITLE
Is this production ready ? 

### ISSUE THREAD

**Issue by olekukonko** [Nik-U/ringsig#1]
Hello, 

Nice work here,  Would like to know 

- If this is production-ready?
- What is your use case?
- Does this suffer from the same issue raised here https://kewde.github.io/urs

Thanks
Regards

**Comment by Nik-U** [comment]
This project is not production-ready for several reasons. Firstly, the only scheme it contains is implemented with `libpbc`, which I would not consider production-ready. Secondly, pairings themselves are arguably not fit for applications that need strong security. Thirdly, the Shacham-Waters ring signature scheme is primarily of academic interest because its main selling point is that it does not require the random oracle model (and it makes performance and security tradeoffs to accomplish this goal), which is not desirable for practical applications. Finally, this project has not been updated in years.

I am archiving the project so that nobody is likely to misinterpret the development state.
